a=int(input("introduce el termino cuadratico "))
b=int(input("introduce el termino lineal "))
c=int(input("introduce el termino independiente "))
x1=(-b+((b**2)-4*a*c)**(1/2))/(2*a)
x2=(-b-((b**2)-4*a*c)**(1/2))/(2*a)
print(x1,x2)